server:
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 3s
    threads:
      max: 10
      min-spare: 2
    max-connections: 20

spring:
  application:
    name: lw-api-tester

  output:
    ansi:
      enabled: detect

  datasource:
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10
      jdbc-url: jdbc:h2:mem:apitest
      driver-class-name: org.h2.Driver
      username: apitester
      password: lonelywolf.pro

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.notasnack.ikare.backoffice: DEBUG

  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5level) %clr([${spring.application.name},%mdc{traceId:-},%mdc{spanId:-}]){magenta} %clr([%15.15thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n%wEx"

management:
  endpoints:
    web:
      exposure:
        include: [ "health" ]